# Generated by Django 6.0.5 on 2026-06-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__record__b72b2d_idx',
            old_name='core_audit__record__idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__app_lab_97a829_idx',
            old_name='core_audit__app_labe_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='app_label',
            field=models.CharField(db_index=True, help_text='操作所属的应用（如 department、employee、authuser）', max_length=50, verbose_name='应用标识'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_code',
            field=models.CharField(db_index=True, help_text='被操作记录的唯一编码（如部门编码、员工工号、用户名等）', max_length=64, verbose_name='记录编码'),
        ),
    ]
