# Generated by Django 6.0.5 on 2026-05-26 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetmanagement', '0005_add_outasset_previous_status'),
        ('usermanagement', '0003_add_department_tree_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('unregistered_code', models.CharField(help_text='系统自动生成的唯一编码，格式：UNR-YYYYMMDD-XXXXXX', max_length=32, unique=True, verbose_name='未登记资产编码')),
                ('scenario_type', models.CharField(choices=[('s1_no_record', '实物有系统无'), ('s2_no_outasset', '系统有无出库'), ('s3_status_mismatch', '状态异常')], help_text='不在账资产的具体场景：S1实物有系统无/S2系统有无出库/S3状态异常', max_length=20, verbose_name='场景类型')),
                ('discovery_date', models.DateField(help_text='发现资产的日期', verbose_name='发现日期')),
                ('discovery_location', models.CharField(help_text='资产发现的具体位置', max_length=200, verbose_name='发现地点')),
                ('asset_name', models.CharField(help_text='资产的名称', max_length=100, verbose_name='资产名称')),
                ('asset_brand', models.CharField(blank=True, help_text='资产的品牌（可选）', max_length=100, null=True, verbose_name='资产品牌')),
                ('asset_specification', models.CharField(blank=True, help_text='资产的规格型号（可选）', max_length=100, null=True, verbose_name='资产规格')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='资产的预估价值（元，可选）', max_digits=10, null=True, verbose_name='预估价值')),
                ('handle_type', models.CharField(blank=True, choices=[('create_and_recycle', '新建资产并回收'), ('create_and_damaged', '新建资产并报废'), ('supplement_and_recycle', '补建记录并回收'), ('correct_and_recycle', '修正状态并回收'), ('reject', '拒绝处理')], help_text='审批后选择的处理方式', max_length=30, null=True, verbose_name='处理方式')),
                ('handle_description', models.TextField(blank=True, help_text='处理的补充说明（可选）', null=True, verbose_name='处理说明')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', help_text='审批的当前状态：待审批/已批准/已拒绝', max_length=20, verbose_name='审批状态')),
                ('approval_date', models.DateField(blank=True, help_text='审批完成的日期', null=True, verbose_name='审批日期')),
                ('approval_remark', models.TextField(blank=True, help_text='审批的备注说明（可选）', null=True, verbose_name='审批备注')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='照片/凭证文件路径列表（JSON数组格式）', verbose_name='附件列表')),
                ('approver_jobcode', models.ForeignKey(blank=True, help_text='审批人的人员工号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_approved', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='审批人')),
                ('asset_type_code', models.ForeignKey(blank=True, help_text='资产的分类（可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_assets', to='assetmanagement.assettype', to_field='asset_type_code', verbose_name='资产类型')),
                ('discovery_person_jobcode', models.ForeignKey(help_text='发现资产的人员工号', on_delete=django.db.models.deletion.DO_NOTHING, related_name='unregistered_discovered', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='发现人')),
                ('related_asset_code', models.ForeignKey(blank=True, help_text='系统中已存在的资产编码（S2/S3场景必填）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_records', to='assetmanagement.asset', to_field='asset_code', verbose_name='关联资产编码')),
                ('result_asset_code', models.ForeignKey(blank=True, help_text='处理后创建的资产编码', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_source', to='assetmanagement.asset', to_field='asset_code', verbose_name='结果资产编码')),
                ('result_damaged_code', models.ForeignKey(blank=True, help_text='处理后创建的待报废记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_source', to='assetmanagement.damagedasset', verbose_name='结果待报废记录')),
                ('result_recycle_code', models.ForeignKey(blank=True, help_text='处理后创建的回收记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_source', to='assetmanagement.recycleasset', verbose_name='结果回收记录')),
                ('target_storage_code', models.ForeignKey(blank=True, help_text='回收后存放的仓库', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_targets', to='assetmanagement.storage', to_field='storage_code', verbose_name='目标仓库')),
            ],
            options={
                'verbose_name': '未登记资产管理',
                'verbose_name_plural': '未登记资产管理',
                'db_table': 'am_unregistered_asset',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unregistered_code'], name='am_unregist_unregis_29b05d_idx'), models.Index(fields=['scenario_type'], name='am_unregist_scenari_297ba8_idx'), models.Index(fields=['approval_status'], name='am_unregist_approva_b9e098_idx'), models.Index(fields=['discovery_person_jobcode'], name='am_unregist_discove_62c158_idx'), models.Index(fields=['discovery_person_jobcode', 'approval_status'], name='am_unregist_discove_c38d4e_idx')],
            },
        ),
    ]
