# Generated by Django 6.0.5 on 2026-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0011_assettype_recordcode_contract_recordcode_and_more'),
        ('unregisteredasset', '0001_initial'),
        ('usermanagement', '0004_department_is_deleted_department_recordcode_and_more'),
    ]

    operations = [
        # Stripped: parallel-branch ops are no-ops
    ]
