# Generated by Django 6.0.5 on 2026-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0011_assettype_recordcode_contract_recordcode_and_more'),
        ('unregisteredasset', '0001_initial'),
        ('usermanagement', '0004_department_is_deleted_department_recordcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredasset',
            name='approver_jobcode',
            field=models.ForeignKey(blank=True, help_text='审批人的人员工号（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_approved', to='usermanagement.employee', to_field='recordcode', verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='unregisteredasset',
            name='asset_type_code',
            field=models.ForeignKey(blank=True, help_text='资产的分类（可选，通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_assets', to='assetmanagement.assettype', to_field='recordcode', verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='unregisteredasset',
            name='discovery_person_jobcode',
            field=models.ForeignKey(help_text='发现资产的人员工号（通过 recordcode 关联）', on_delete=django.db.models.deletion.DO_NOTHING, related_name='unregistered_discovered', to='usermanagement.employee', to_field='recordcode', verbose_name='发现人'),
        ),
        migrations.AlterField(
            model_name='unregisteredasset',
            name='related_asset_code',
            field=models.ForeignKey(blank=True, help_text='系统中已存在的资产编码（S2/S3场景必填，通过 asset_recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_records', to='assetmanagement.asset', to_field='asset_recordcode', verbose_name='关联资产编码'),
        ),
        migrations.AlterField(
            model_name='unregisteredasset',
            name='result_asset_code',
            field=models.ForeignKey(blank=True, help_text='处理后创建的资产编码（通过 asset_recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_source', to='assetmanagement.asset', to_field='asset_recordcode', verbose_name='结果资产编码'),
        ),
        migrations.AlterField(
            model_name='unregisteredasset',
            name='target_storage_code',
            field=models.ForeignKey(blank=True, help_text='回收后存放的仓库（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_targets', to='assetmanagement.storage', to_field='recordcode', verbose_name='目标仓库'),
        ),
    ]
