# Generated by Django 6.0.5 on 2026-06-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('auth_id', models.AutoField(help_text='用户唯一标识', primary_key=True, serialize=False, verbose_name='用户ID')),
                ('recordcode', models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=32, null=True, unique=True, verbose_name='记录编码')),
                ('auth_username', models.CharField(help_text='用户登录名，唯一标识', max_length=150, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, help_text='用户邮箱地址', max_length=254, null=True, verbose_name='电子邮件')),
                ('auth_is_active', models.BooleanField(default=True, help_text='用户账户是否激活', verbose_name='是否激活')),
                ('auth_is_staff', models.BooleanField(default=False, help_text='是否为后台管理员', verbose_name='是否为员工')),
                ('auth_date_create', models.DateTimeField(auto_now_add=True, help_text='用户创建时间', verbose_name='创建日期')),
                ('auth_date_update', models.DateTimeField(auto_now=True, help_text='用户信息更新时间', verbose_name='更新日期')),
                ('auth_phone', models.CharField(help_text='用户联系电话', max_length=15, verbose_name='联系电话')),
                ('last_login', models.DateTimeField(blank=True, help_text='用户最后一次登录时间', null=True, verbose_name='上次登录时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '认证与用户管理',
                'verbose_name_plural': '认证与用户管理',
                'db_table': 'auth_user_management_table',
                'ordering': ['auth_username'],
                'indexes': [models.Index(fields=['auth_username'], name='auth_user_m_auth_us_008906_idx'), models.Index(fields=['email'], name='auth_user_m_email_a42132_idx'), models.Index(fields=['auth_phone'], name='auth_user_m_auth_ph_7732d4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('auth_is_active', True)), fields=('auth_username',), name='unique_auth_username_active'), models.UniqueConstraint(condition=models.Q(('auth_is_active', True)), fields=('email',), name='unique_auth_email_active'), models.UniqueConstraint(condition=models.Q(('auth_is_active', True)), fields=('auth_phone',), name='unique_auth_phone_active')],
            },
        ),
    ]
