# Generated by Django 6.0.5 on 2026-05-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authusermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'ordering': ['auth_username'], 'verbose_name': '认证与用户管理', 'verbose_name_plural': '认证与用户管理'},
        ),
    ]
