# Generated by Django 5.2.3 on 2026-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusermanagement', '0002_alter_authuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='是否为超级管理员', verbose_name='超级管理员'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码'),
        ),
    ]
