# Generated by Django 6.0.5 on 2026-06-11 04:13

from django.db import migrations, models


def fill_authuser_recordcodes(apps, schema_editor):
    """为现有 AuthUser 数据生成 recordcode"""
    AuthUser = apps.get_model('authusermanagement', 'AuthUser')
    import uuid
    from datetime import datetime
    for obj in AuthUser.objects.all():
        if not obj.recordcode:
            obj.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            obj.save(update_fields=['recordcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authusermanagement', '0002_alter_authuser_options'),
    ]

    operations = [
        # Stripped: parallel-branch ops are no-ops
    ]
