# Generated by Django 5.2.3 on 2026-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusermanagement', '0002_alter_authuser_groups_and_more'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
