# Generated by Django 5.2.17 on 2026-08-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authusermanagement', '0003_alter_authuser_is_superuser_and_more'),
        ('authusermanagement', '0004_fill_recordcodes'),
    ]

    operations = [
    ]
