# Generated by Django 5.2.17 on 2026-08-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authusermanagement', '0005_merge_20260824_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='authuser_set', related_query_name='authuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='是否为超级管理员', verbose_name='超级管理员'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='authuser_set', related_query_name='authuser', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
