# Generated by Django 6.0.5 on 2026-05-08 15:42

import apps.assetmanagement.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('asset_recordcode', models.CharField(blank=True, db_index=True, help_text='系统自动生成的入库记录编码', max_length=32, null=True, unique=True, verbose_name='记录编码')),
                ('asset_code', models.CharField(editable=False, help_text='资产唯一编码，不可修改', max_length=20, unique=True, verbose_name='资产编码')),
                ('asset_name', models.CharField(help_text='资产的名称', max_length=100, verbose_name='资产名称')),
                ('asset_purchase_price', models.DecimalField(decimal_places=2, help_text='资产采购单价（元）', max_digits=10, verbose_name='资产购买价格')),
                ('asset_purchase_number', models.IntegerField(default=1, help_text='采购数量', verbose_name='资产购买数量')),
                ('asset_unit', models.CharField(blank=True, help_text='计量单位：台/套/个等', max_length=50, null=True, verbose_name='资产单位')),
                ('asset_brand', models.CharField(blank=True, help_text='资产的品牌', max_length=100, null=True, verbose_name='资产品牌')),
                ('asset_specification', models.CharField(blank=True, help_text='资产的规格型号', max_length=100, null=True, verbose_name='资产规格')),
                ('asset_purchase_date', models.DateField(help_text='资产采购的日期', verbose_name='资产购买日期')),
                ('asset_warranty_period', models.IntegerField(blank=True, default=0, help_text='资产保修期限（年）', null=True, verbose_name='保修期（年）')),
                ('asset_entry_date', models.DateField(help_text='资产入库的日期', verbose_name='入库日期')),
                ('asset_using_location', models.CharField(blank=True, help_text='资产使用的地点', max_length=100, null=True, verbose_name='资产使用地点')),
                ('asset_appearance', models.CharField(blank=True, choices=[('newly', '新增加资产'), ('used', '已使用资产'), ('damaged', '待报废资产'), ('waste', '已报废资产')], default='newly', help_text='资产外观状态', max_length=20, null=True, verbose_name='资产外观')),
                ('asset_current_status', models.CharField(choices=[('in_store', '在库资产'), ('in_use', '在用资产'), ('in_scrapped', '报废资产')], default='in_store', help_text='用于跟踪资产当前所处的流程阶段：在库/在用/报废', max_length=20, verbose_name='资产当前状态')),
                ('using_record', models.TextField(blank=True, help_text='资产使用历史记录', null=True, verbose_name='使用记录')),
                ('asset_description', models.TextField(blank=True, help_text='资产的补充说明', null=True, verbose_name='资产描述')),
                ('asset_applicant_jobcode', models.ForeignKey(blank=True, help_text='资产申请人的工号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_applicant', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='资产申请人工号')),
                ('asset_entry_person_jobcode', models.ForeignKey(blank=True, help_text='办理入库的人员工号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_entry', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='资产入库人工号')),
                ('asset_manager_jobcode', models.ForeignKey(blank=True, help_text='资产保管人的工号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_manager', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='资产保管人')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
                'db_table': 'am_asset',
            },
        ),
        migrations.CreateModel(
            name='Assetdatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '资产管理(兼容)',
                'verbose_name_plural': '资产管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.asset',),
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('asset_type_code', models.CharField(help_text='资产类型唯一编码', max_length=20, unique=True, verbose_name='资产分类编码')),
                ('asset_type_secondary', models.CharField(help_text='资产的细分类，如台式机/笔记本等', max_length=100, verbose_name='资产二级分类名称')),
                ('asset_type_primary', models.CharField(help_text='资产的大类，如办公设备/网络设备等', max_length=100, verbose_name='资产一级分类名称')),
                ('asset_type_category', models.CharField(blank=True, choices=[('hardware', '硬件'), ('software', '软件'), ('other', '其他')], default='hardware', help_text='分类类型：硬件/软件/其他', max_length=50, null=True, verbose_name='资产分类类型')),
                ('asset_type_description', models.TextField(blank=True, help_text='资产分类的补充说明', null=True, verbose_name='资产分类类型描述')),
            ],
            options={
                'verbose_name': '资产分类管理',
                'verbose_name_plural': '资产分类管理',
                'db_table': 'am_asset_type',
                'indexes': [models.Index(fields=['asset_type_code'], name='am_asset_ty_asset_t_cb5144_idx'), models.Index(fields=['asset_type_category'], name='am_asset_ty_asset_t_3bc5d5_idx')],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type_code',
            field=models.ForeignKey(help_text='关联的资产类型', on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets', to='assetmanagement.assettype', to_field='asset_type_code', verbose_name='资产类型'),
        ),
        migrations.CreateModel(
            name='Assettypedatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '资产类型管理(兼容)',
                'verbose_name_plural': '资产类型管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.assettype',),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('contract_code', models.CharField(help_text='合同唯一编码', max_length=20, unique=True, verbose_name='合同编码')),
                ('contract_name', models.CharField(help_text='合同的完整名称', max_length=100, unique=True, verbose_name='合同名称')),
                ('contract_type', models.CharField(blank=True, choices=[('purchase', '采购合同'), ('service', '服务合同'), ('information_construction', '信息化建设合同'), ('direct_procurement', '直接采购合同')], default='purchase', help_text='合同类型：采购/服务/信息化/直接采购', max_length=50, null=True, verbose_name='合同类型')),
                ('contract_price', models.DecimalField(decimal_places=2, help_text='合同总金额（元）', max_digits=10, verbose_name='合同金额')),
                ('contract_supplier', models.CharField(help_text='合同供应商名称', max_length=100, verbose_name='合同供应商')),
                ('contract_signing_date', models.DateField(help_text='合同签署的日期', verbose_name='合同签订日期')),
                ('contract_warranty_period', models.IntegerField(default=0, help_text='合同规定的保修期限（年）', verbose_name='保修期（年）')),
                ('contract_preliminary_acceptance_date', models.DateField(blank=True, help_text='初步验收的日期', null=True, verbose_name='初验日期')),
                ('contract_final_acceptance_date', models.DateField(blank=True, help_text='最终验收的日期', null=True, verbose_name='终验日期')),
                ('contract_settlment_status', models.CharField(choices=[('pending', '待结算'), ('settled', '已结算')], default='pending', help_text='合同的结算状态：待结算/已结算', max_length=20, verbose_name='结算状态')),
                ('contract_settlment_price', models.DecimalField(blank=True, decimal_places=2, help_text='实际结算的金额（元）', max_digits=10, null=True, verbose_name='结算金额')),
                ('contract_paid_count_number', models.IntegerField(default=0, help_text='已付款的次数', verbose_name='已付次数')),
                ('contract_paid_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='累计已付款金额（元）', max_digits=10, null=True, verbose_name='已付金额')),
                ('contract_paid_record', models.TextField(blank=True, help_text='每次付款的详细记录', null=True, verbose_name='付款记录')),
            ],
            options={
                'verbose_name': '合同管理',
                'verbose_name_plural': '合同管理',
                'db_table': 'am_contract',
                'indexes': [models.Index(fields=['contract_code'], name='am_contract_contrac_ebab44_idx'), models.Index(fields=['contract_type'], name='am_contract_contrac_e52d21_idx'), models.Index(fields=['contract_settlment_status'], name='am_contract_contrac_8372cb_idx')],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_contract_code',
            field=models.ForeignKey(blank=True, db_column='asset_contract_code', help_text='关联的采购合同', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assetmanagement.contract', to_field='contract_code', verbose_name='资产合同'),
        ),
        migrations.CreateModel(
            name='Contractdatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '合同管理(兼容)',
                'verbose_name_plural': '合同管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.contract',),
        ),
        migrations.CreateModel(
            name='DamagedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('damaged_asset_number', models.IntegerField(default=1, help_text='待报废的资产数量', verbose_name='待报废数量')),
                ('damaged_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='提交报废申请的日期', null=True, verbose_name='待报废日期')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', help_text='审批状态：待审批/已批准/已拒绝', max_length=20, verbose_name='报废审批状态')),
                ('damaged_asset_description', models.TextField(blank=True, help_text='报废原因等说明', null=True, verbose_name='待报废资产描述')),
                ('approver', models.ForeignKey(blank=True, help_text='审批人的工号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='damaged_assets_approver', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='审批人')),
                ('damaged_asset_code', models.OneToOneField(blank=True, help_text='待报废的资产编码', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_asset', to='assetmanagement.asset', to_field='asset_code', verbose_name='待报废资产编码')),
                ('damaged_asset_contract_code', models.ForeignKey(blank=True, help_text='关联的合同编码', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_assets', to='assetmanagement.contract', to_field='contract_code', verbose_name='待报废资产合同编码')),
            ],
            options={
                'verbose_name': '待报废资产管理',
                'verbose_name_plural': '待报废资产管理',
                'db_table': 'am_damaged_asset',
            },
        ),
        migrations.CreateModel(
            name='Damagedassetdatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '待报废资产管理(兼容)',
                'verbose_name_plural': '待报废资产管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.damagedasset',),
        ),
        migrations.CreateModel(
            name='HardDiskSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('harddisk_number', models.IntegerField(help_text='该资产下的硬盘数量', verbose_name='硬盘数量')),
                ('harddisk_no', models.IntegerField(default=1, help_text='硬盘在资产中的序号', verbose_name='硬盘编号')),
                ('harddisk_sn_code', models.CharField(help_text='硬盘的唯一序列号', max_length=100, unique=True, verbose_name='硬盘序列号')),
                ('harddisk_type', models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe'), ('Other', 'Other')], default='HDD', help_text='硬盘类型：HDD/SSD/NVMe', max_length=100, null=True, verbose_name='硬盘类型')),
                ('harddisk_sn_description', models.TextField(blank=True, help_text='硬盘的补充说明', null=True, verbose_name='硬盘序列号描述')),
                ('harddisk_status', models.CharField(choices=[('active', '正常'), ('repair', '维修'), ('scrap', '报废'), ('lost', '丢失'), ('damaged', '损坏')], default='active', help_text='硬盘状态：正常/维修/报废/丢失/损坏', max_length=10, verbose_name='硬盘序列号资产状态')),
                ('asset_code', models.ForeignKey(help_text='关联的资产编码', on_delete=django.db.models.deletion.CASCADE, related_name='harddisk_sns', to='assetmanagement.asset', to_field='asset_code', verbose_name='硬盘序列号对应资产编码')),
            ],
            options={
                'verbose_name': '硬盘序列号管理',
                'verbose_name_plural': '硬盘序列号管理',
                'db_table': 'am_hard_disk_sn',
            },
        ),
        migrations.CreateModel(
            name='HardDiskSNdatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '硬盘序列号管理(兼容)',
                'verbose_name_plural': '硬盘序列号管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.harddisksn',),
        ),
        migrations.CreateModel(
            name='OutAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('outasset_recordcode', models.CharField(default=apps.assetmanagement.models.generate_outassetrecordcode, help_text='格式：OUT-20201223-XXXXXXXX', max_length=36, unique=True, verbose_name='出库记录唯一标识')),
                ('outasset_number', models.IntegerField(default=1, help_text='出库的资产数量', verbose_name='出库数量')),
                ('outasset_current_status', models.CharField(choices=[('in_use', '在用资产'), ('recycled', '已回收资产')], default='in_use', help_text='出库资产的状态：在用/已回收', max_length=20, verbose_name='出库资产状态')),
                ('return_date', models.DateField(blank=True, help_text='借用资产的预计或实际归还日期', null=True, verbose_name='归还日期')),
                ('outasset_using_location', models.CharField(help_text='资产使用的位置', max_length=200, verbose_name='出库资产使用地点')),
                ('outasset_date', models.DateField(default=django.utils.timezone.now, help_text='资产出库的日期', verbose_name='出库日期')),
                ('outasset_type', models.CharField(blank=True, choices=[('receive', '领用'), ('borrow', '借用')], default='receive', help_text='出库类型：领用/借用', max_length=50, null=True, verbose_name='出库类型')),
                ('outasset_description', models.TextField(blank=True, help_text='出库的补充说明', null=True, verbose_name='出库资产描述')),
                ('outasset_applicant_jobcode', models.ForeignKey(blank=True, help_text='资产申请人的工号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='out_assets_applicant', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='出库资产申请人')),
                ('outasset_code', models.ForeignKey(blank=True, help_text='关联的资产编码', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_assets', to='assetmanagement.asset', to_field='asset_code', verbose_name='出库资产编码')),
                ('outasset_contract_code', models.ForeignKey(blank=True, help_text='关联的合同编码', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_assets', to='assetmanagement.contract', to_field='contract_code', verbose_name='关联合同编码')),
                ('outasset_manager_jobcode', models.ForeignKey(help_text='资产保管人的工号', on_delete=django.db.models.deletion.DO_NOTHING, related_name='out_assets_manager', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='出库资产保管人')),
            ],
            options={
                'verbose_name': '出库资产管理',
                'verbose_name_plural': '出库资产管理',
                'db_table': 'am_out_asset',
            },
        ),
        migrations.CreateModel(
            name='Outassetdatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '出库资产管理(兼容)',
                'verbose_name_plural': '出库资产管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.outasset',),
        ),
        migrations.CreateModel(
            name='RecycleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('recycle_asset_number', models.IntegerField(default=1, help_text='回收的资产数量', verbose_name='回收数量')),
                ('recycle_asset_date', models.DateField(help_text='资产回收的日期', verbose_name='回收日期')),
                ('recycle_asset_description', models.TextField(blank=True, help_text='回收的补充说明', null=True, verbose_name='回收资产描述')),
                ('outasset_recordcode', models.OneToOneField(help_text='关联的出库记录编码', on_delete=django.db.models.deletion.CASCADE, related_name='recycle_record', to='assetmanagement.outasset', to_field='outasset_recordcode', verbose_name='对应的出库记录编码')),
                ('recycle_asset_code', models.ForeignKey(help_text='回收的资产编码', on_delete=django.db.models.deletion.PROTECT, related_name='recycle_assets', to='assetmanagement.asset', to_field='asset_code', verbose_name='回收资产编码')),
                ('recycle_asset_recycle_person_jobcode', models.ForeignKey(help_text='办理回收的人员工号', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recycle_assets_recycle', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='回收资产回收人工号')),
                ('recycle_asset_using_person_jobcode', models.ForeignKey(default='', help_text='资产使用人的工号', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recycle_assets_using', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='回收资产使用人工号')),
            ],
            options={
                'verbose_name': '回收资产管理',
                'verbose_name_plural': '回收资产管理',
                'db_table': 'am_recycle_asset',
            },
        ),
        migrations.CreateModel(
            name='Recycleassetdatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '回收资产管理(兼容)',
                'verbose_name_plural': '回收资产管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.recycleasset',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('storage_code', models.CharField(help_text='仓库唯一编码，用于业务关联', max_length=20, unique=True, verbose_name='仓库编码')),
                ('storage_name', models.CharField(help_text='仓库名称，用户可见的展示名称', max_length=100, unique=True, verbose_name='仓库名称')),
                ('storage_address', models.CharField(help_text='仓库的物理地址', max_length=200, verbose_name='仓库地址')),
                ('storage_type', models.CharField(blank=True, choices=[('newasset', '新货仓库'), ('recycle', '回收仓库'), ('damaged', '待报废仓库')], default='newasset', help_text='仓库类型：新货/回收/待报废', max_length=50, null=True, verbose_name='仓库类型')),
                ('storage_description', models.TextField(blank=True, help_text='仓库的补充说明信息', null=True, verbose_name='仓库描述')),
            ],
            options={
                'verbose_name': '仓库管理',
                'verbose_name_plural': '仓库管理',
                'db_table': 'am_storage',
                'indexes': [models.Index(fields=['storage_code'], name='am_storage_storage_8e5c92_idx'), models.Index(fields=['storage_type'], name='am_storage_storage_a54307_idx')],
            },
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='recycle_asset_storage_code',
            field=models.ForeignKey(help_text='回收后存放的仓库', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recycle_assets', to='assetmanagement.storage', to_field='storage_code', verbose_name='回收资产存储仓库'),
        ),
        migrations.AddField(
            model_name='damagedasset',
            name='damaged_asset_storage_code',
            field=models.ForeignKey(help_text='资产存放的仓库', on_delete=django.db.models.deletion.DO_NOTHING, related_name='damaged_assets', to='assetmanagement.storage', to_field='storage_code', verbose_name='待报废资产存储仓库'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_storage_code',
            field=models.ForeignKey(blank=True, help_text='资产当前所在仓库', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets', to='assetmanagement.storage', to_field='storage_code', verbose_name='存储仓库'),
        ),
        migrations.CreateModel(
            name='Storagedatabasetable',
            fields=[
            ],
            options={
                'verbose_name': '仓库管理(兼容)',
                'verbose_name_plural': '仓库管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.storage',),
        ),
        migrations.CreateModel(
            name='WasteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('waste_asset_number', models.IntegerField(default=1, help_text='报废的资产数量', verbose_name='已报废数量')),
                ('waste_asset_date', models.DateField(help_text='完成报废的日期', verbose_name='报废日期')),
                ('waste_asset_description', models.TextField(blank=True, help_text='报废的补充说明', null=True, verbose_name='报废资产描述')),
                ('waste_asset_code', models.OneToOneField(help_text='已报废的资产编码', on_delete=django.db.models.deletion.DO_NOTHING, related_name='waste_asset', to='assetmanagement.asset', to_field='asset_code', verbose_name='已报废资产编码')),
                ('waste_asset_contract_code', models.ForeignKey(help_text='关联的合同编码', on_delete=django.db.models.deletion.DO_NOTHING, related_name='waste_assets', to='assetmanagement.contract', to_field='contract_code', verbose_name='已报废资产合同编码')),
            ],
            options={
                'verbose_name': '已报废资产管理',
                'verbose_name_plural': '已报废资产管理',
                'db_table': 'am_waste_asset',
            },
        ),
        migrations.CreateModel(
            name='Wasteassettable',
            fields=[
            ],
            options={
                'verbose_name': '已报废资产管理(兼容)',
                'verbose_name_plural': '已报废资产管理(兼容)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assetmanagement.wasteasset',),
        ),
        migrations.AddIndex(
            model_name='harddisksn',
            index=models.Index(fields=['harddisk_sn_code'], name='am_hard_dis_harddis_e1d258_idx'),
        ),
        migrations.AddIndex(
            model_name='harddisksn',
            index=models.Index(fields=['asset_code'], name='am_hard_dis_asset_c_7977e2_idx'),
        ),
        migrations.AddIndex(
            model_name='harddisksn',
            index=models.Index(fields=['harddisk_status'], name='am_hard_dis_harddis_d99692_idx'),
        ),
        migrations.AddIndex(
            model_name='outasset',
            index=models.Index(fields=['outasset_recordcode'], name='am_out_asse_outasse_9060e3_idx'),
        ),
        migrations.AddIndex(
            model_name='outasset',
            index=models.Index(fields=['outasset_code'], name='am_out_asse_outasse_50b277_idx'),
        ),
        migrations.AddIndex(
            model_name='outasset',
            index=models.Index(fields=['outasset_current_status'], name='am_out_asse_outasse_9bed11_idx'),
        ),
        migrations.AddIndex(
            model_name='recycleasset',
            index=models.Index(fields=['outasset_recordcode'], name='am_recycle__outasse_c9582f_idx'),
        ),
        migrations.AddIndex(
            model_name='recycleasset',
            index=models.Index(fields=['recycle_asset_code'], name='am_recycle__recycle_6df88e_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedasset',
            index=models.Index(fields=['damaged_asset_code'], name='am_damaged__damaged_2b04dc_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedasset',
            index=models.Index(fields=['approval_status'], name='am_damaged__approva_401841_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_recordcode'], name='am_asset_asset_r_b55e31_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_code'], name='am_asset_asset_c_5d1ace_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_current_status'], name='am_asset_asset_c_df414a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type_code'], name='am_asset_asset_t_cc00c5_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_storage_code'], name='am_asset_asset_s_51c492_idx'),
        ),
        migrations.AddIndex(
            model_name='wasteasset',
            index=models.Index(fields=['waste_asset_code'], name='am_waste_as_waste_a_a6cb33_idx'),
        ),
    ]
