# Generated by Django 6.0.5 on 2026-05-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0001_initial'),
        ('usermanagement', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(db_index=True, help_text='关联的资产编码', max_length=20, verbose_name='资产编码')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('out', '出库'), ('recycle', '回收'), ('damaged', '待报废'), ('waste', '已报废'), ('approve', '审批'), ('transfer', '转移')], db_index=True, help_text='操作类型：创建/更新/删除/出库/回收/待报废/已报废/审批/转移', max_length=20, verbose_name='操作类型')),
                ('operation_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='操作执行的时间', verbose_name='操作时间')),
                ('operator_jobcode', models.CharField(blank=True, help_text='执行操作的人员工号', max_length=20, null=True, verbose_name='操作人工号')),
                ('operator_name', models.CharField(blank=True, help_text='执行操作的人员姓名', max_length=100, null=True, verbose_name='操作人姓名')),
                ('before_data', models.JSONField(blank=True, help_text='操作前的资产数据（JSON格式）', null=True, verbose_name='变更前数据')),
                ('after_data', models.JSONField(blank=True, help_text='操作后的资产数据（JSON格式）', null=True, verbose_name='变更后数据')),
                ('description', models.TextField(help_text='操作的详细描述', verbose_name='操作描述')),
                ('related_record_code', models.CharField(blank=True, help_text='关联的业务记录编码，如出库单号', max_length=50, null=True, verbose_name='关联记录编码')),
                ('related_record_type', models.CharField(blank=True, help_text='关联记录的类型：out/recycle/damaged/waste', max_length=20, null=True, verbose_name='关联记录类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='执行操作的IP地址', null=True, verbose_name='操作IP地址')),
            ],
            options={
                'verbose_name': '资产操作记录',
                'verbose_name_plural': '资产操作记录',
                'db_table': 'am_asset_operation_log',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'verbose_name': '资产管理', 'verbose_name_plural': '资产管理'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_appearance',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='using_record',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_current_status',
            field=models.CharField(choices=[('in_store', '在库'), ('recycled_pending', '已回收待发放'), ('in_use', '在用'), ('damaged', '待报废'), ('scrapped', '已报废')], db_index=True, default='in_store', help_text='资产状态：在库/已回收待发放/在用/待报废/已报废', max_length=20, verbose_name='资产当前状态'),
        ),
        migrations.AlterField(
            model_name='recycleasset',
            name='recycle_asset_using_person_jobcode',
            field=models.ForeignKey(blank=True, default=None, help_text='资产使用人的工号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycle_assets_using', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='回收资产使用人工号'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-created_at'], name='am_asset_created_9d56c2_idx'),
        ),
        migrations.AddIndex(
            model_name='outasset',
            index=models.Index(fields=['outasset_date'], name='am_out_asse_outasse_7cbbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='assetoperationlog',
            index=models.Index(fields=['asset_code', '-operation_time'], name='am_asset_op_asset_c_53fc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='assetoperationlog',
            index=models.Index(fields=['operation_type', '-operation_time'], name='am_asset_op_operati_c5e024_idx'),
        ),
        migrations.AddIndex(
            model_name='assetoperationlog',
            index=models.Index(fields=['operator_jobcode', '-operation_time'], name='am_asset_op_operato_b047bf_idx'),
        ),
        migrations.AddIndex(
            model_name='assetoperationlog',
            index=models.Index(fields=['asset_code', 'operation_type'], name='am_asset_op_asset_c_d227ca_idx'),
        ),
    ]
