# Generated by Django 5.2.3 on 2026-07-13 02:44

import django.db.models.deletion
from django.db import migrations, models


def convert_parent_code_to_fk(apps, schema_editor):
    """
    数据迁移:将 parent_code(type_code)转换为 parent FK(recordcode),
    并自动生成物化路径 path。
    """
    AssetType = apps.get_model('assetmanagement', 'AssetType')

    # 1. 建立 type_code → recordcode 映射
    code_to_rc = {}
    for at in AssetType.objects.filter(is_deleted=False):
        code_to_rc[at.type_code] = at.recordcode

    # 2. 转换 parent_code → parent FK
    updated_count = 0
    for at in AssetType.objects.filter(is_deleted=False, parent_code__isnull=False):
        parent_rc = code_to_rc.get(at.parent_code)
        if parent_rc:
            AssetType.objects.filter(pk=at.pk).update(parent_id=parent_rc)
            updated_count += 1
        else:
            print(f"  [WARN] 类型 {at.type_code} 的父级 {at.parent_code} 不存在,跳过")

    print(f"  [INFO] 转换 parent FK 完成:{updated_count} 条记录")

    # 3. 生成物化路径 path
    rc_map = {}
    for at in AssetType.objects.filter(is_deleted=False):
        rc_map[at.recordcode] = at

    def generate_path(at):
        if at.parent_id is None:
            return f"/{at.type_code}"
        parent = rc_map.get(at.parent_id)
        if parent:
            parent_path = generate_path(parent)
            return f"{parent_path}/{at.type_code}"
        return f"/{at.type_code}"

    path_updated = 0
    all_types = list(AssetType.objects.filter(is_deleted=False).order_by('level', 'sort_order'))
    for at in all_types:
        new_path = generate_path(at)
        AssetType.objects.filter(pk=at.pk).update(path=new_path)
        path_updated += 1

    print(f"  [INFO] 生成物化路径完成:{path_updated} 条记录")


def reverse_convert(apps, schema_editor):
    """反向迁移"""
    AssetType = apps.get_model('assetmanagement', 'AssetType')
    AssetType.objects.all().update(parent=None, path='')


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assettype',
            new_name='idx_asset_type_parent_old',
            old_name='am_asset_ty_parent__8acf11_idx',
        ),
        migrations.AddField(
            model_name='assettype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父级资产类型(FK 指向 recordcode),null 表示顶级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assetmanagement.assettype', to_field='recordcode', verbose_name='父级类型'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='path',
            field=models.CharField(blank=True, default='', help_text='从根到当前节点的完整路径,如 /ASSETTYPE-001/IT-001/DEV-001', max_length=500, verbose_name='物化路径'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='parent_code',
            field=models.CharField(blank=True, help_text='【已废弃】迁移完成后将删除,新代码请使用 parent FK', max_length=32, null=True, verbose_name='父级编码(旧)'),
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['parent'], name='idx_asset_type_parent_fk'),
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['path'], name='idx_asset_type_path'),
        ),
        # 数据迁移:parent_code → parent FK + 生成 path
        migrations.RunPython(convert_parent_code_to_fk, reverse_convert),
    ]
