# Generated by Django 6.0.5 on 2026-05-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0001_initial'),
        ('usermanagement', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
