# Generated by Django 5.2.3 on 2026-07-14 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0002_rename_am_asset_ty_parent__8acf11_idx_idx_asset_type_parent_old_and_more'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
