# Generated by Django 6.0.5 on 2026-05-24 12:03
# 修改：拆分 logging_id 字段添加为两步，避免历史数据唯一约束冲突

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0002_assetoperationlog_alter_asset_options_and_more'),
    ]

    operations = [
        # 步骤1：先添加 logging_id 字段（不设置唯一约束），允许历史数据为空字符串
        migrations.AddField(
            model_name='assetoperationlog',
            name='logging_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='系统自动生成的日志记录唯一标识，格式：操作类型-Log-日期-随机字符',
                max_length=50,
                verbose_name='日志记录ID',
            ),
        ),
        # 步骤2：添加其他字段变更（与原迁移一致）
        migrations.AddField(
            model_name='wasteasset',
            name='source_damaged_asset',
            field=models.OneToOneField(blank=True, help_text='关联的待报废记录，用于追溯来源', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='waste_asset_record', to='assetmanagement.damagedasset', verbose_name='来源待报废记录'),
        ),
        migrations.AlterField(
            model_name='outasset',
            name='outasset_current_status',
            field=models.CharField(choices=[('in_use', '在用资产'), ('recycled_pending', '已回收待发放'), ('damaged', '待报废'), ('scrapped', '已报废')], default='in_use', help_text='出库资产的状态：在用/已回收待发放/待报废/已报废', max_length=20, verbose_name='出库资产状态'),
        ),
        migrations.AddIndex(
            model_name='wasteasset',
            index=models.Index(fields=['source_damaged_asset'], name='am_waste_as_source__16c07e_idx'),
        ),
    ]
