# Generated by Django 6.0.5 on 2026-05-24 12:03
# 修改：拆分 logging_id 字段添加为两步，避免历史数据唯一约束冲突

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0002_assetoperationlog_alter_asset_options_and_more'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
