# Generated by Django 6.0.5 on 2026-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0003_alter_assetoperationlog_operation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_current_status',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], db_index=True, default='in_store', help_text='资产状态：在库/已回收待发放/在用/已损坏/维修中/已遗失/待报废/已报废', max_length=20, verbose_name='资产当前状态'),
        ),
    ]
