# Generated by Django 6.0.5 on 2026-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0004_assetoperationlog_logging_id_unique'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
