# Generated by Django 6.0.5 on 2026-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0004_alter_asset_asset_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleasset',
            name='broken_reason',
            field=models.CharField(blank=True, help_text='回收时发现损坏的原因', max_length=100, null=True, verbose_name='损坏原因'),
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='is_broken',
            field=models.BooleanField(default=False, help_text='回收时是否发现资产损坏', verbose_name='回收时发现损坏'),
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='is_lost',
            field=models.BooleanField(default=False, help_text='回收时是否发现资产遗失', verbose_name='回收时发现遗失'),
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='lost_reason',
            field=models.CharField(blank=True, help_text='回收时发现遗失的原因', max_length=100, null=True, verbose_name='遗失原因'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='physical_grade',
            field=models.CharField(choices=[('excellent', '全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='good', help_text='资产物理成色:全新/良好/一般/较差', max_length=20, verbose_name='物理成色'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usage_type',
            field=models.CharField(choices=[('new', '全新'), ('used', '二手'), ('refurbished', '翻新')], default='new', help_text='资产使用性质:全新/二手/翻新', max_length=20, verbose_name='使用性质'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='from_state',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], help_text='变更前的资产状态', max_length=20, verbose_name='变更前状态'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='to_state',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], help_text='变更后的资产状态', max_length=20, verbose_name='变更后状态'),
        ),
        migrations.AlterField(
            model_name='damagedasset',
            name='original_status',
            field=models.CharField(blank=True, choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失')], help_text='进入damaged前的资产状态,用于reject时回退', max_length=20, null=True, verbose_name='原状态'),
        ),
        migrations.AlterField(
            model_name='recycleasset',
            name='recycle_type',
            field=models.CharField(blank=True, choices=[('normal', '正常回收'), ('abnormal', '异常回收'), ('other', '其他')], help_text='回收原因/类型', max_length=50, null=True, verbose_name='回收类型'),
        ),
        migrations.AlterField(
            model_name='repairasset',
            name='physical_grade_after',
            field=models.CharField(blank=True, choices=[('excellent', '全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], help_text='维修后的物理成色', max_length=20, null=True, verbose_name='维修后成色'),
        ),
        migrations.AlterField(
            model_name='repairasset',
            name='physical_grade_before',
            field=models.CharField(blank=True, choices=[('excellent', '全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], help_text='维修前的物理成色', max_length=20, null=True, verbose_name='维修前成色'),
        ),
    ]
