# Generated by Django 6.0.5 on 2026-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0005_add_outasset_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outasset',
            name='outasset_current_status',
            field=models.CharField(choices=[('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('damaged', '待报废'), ('scrapped', '已报废')], default='in_use', help_text='出库资产的状态：在用/已回收待发放/待报废/已报废', max_length=20, verbose_name='出库资产状态'),
        ),
    ]
