# Generated by Django 6.0.5 on 2026-06-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0006_alter_outasset_outasset_current_status'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
