# Generated by Django 5.2.3 on 2026-07-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0006_add_unique_active_repair_constraint'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
