# Generated by Django 6.0.5 on 2026-06-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0006_alter_outasset_outasset_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(editable=False, help_text='资产唯一编码，不可修改', max_length=64, unique=True, verbose_name='资产编码'),
        ),
    ]
