# Generated by Django 5.2.3 on 2026-07-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0007_remove_asset_state_log'),
        ('usermanagement', '0004_employee_role'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
