# Generated by Django 5.2.3 on 2026-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0008_add_asset_state_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warranty_manually_modified',
            field=models.BooleanField(default=False, help_text='标记保修期是否被手动修改过,防止合同质保期同步时覆盖', verbose_name='保修期是否手动修改'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_warranty_period',
            field=models.IntegerField(blank=True, help_text='合同约定的质保期,可作为资产保修期的默认值', null=True, verbose_name='合同质保期(年)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='has_payment',
            field=models.BooleanField(default=False, help_text='是否有支付记录', verbose_name='是否有支付记录'),
        ),
    ]
