# Generated by Django 5.2.3 on 2026-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0008_add_asset_state_log'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
