# Generated by Django 6.0.5 on 2026-06-08 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0009_fill_recycle_record_code_unique'),
        ('usermanagement', '0003_add_department_tree_fields'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
