# Generated by Django 6.0.5 on 2026-06-08 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0009_fill_recycle_record_code_unique'),
        ('usermanagement', '0003_add_department_tree_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='outasset',
            name='am_out_asse_outasse_9bed11_idx',
        ),
        migrations.RenameIndex(
            model_name='recycleasset',
            new_name='am_recycle__recycle_3c3295_idx',
            old_name='am_recycle_asset_recycle_record_code_idx',
        ),
        migrations.RemoveField(
            model_name='damagedasset',
            name='damaged_asset_contract_code',
        ),
        migrations.RemoveField(
            model_name='damagedasset',
            name='damaged_asset_storage_code',
        ),
        migrations.RemoveField(
            model_name='recycleasset',
            name='recycle_asset_recycle_person_jobcode',
        ),
        migrations.RemoveField(
            model_name='recycleasset',
            name='recycle_asset_storage_code',
        ),
        migrations.RemoveField(
            model_name='recycleasset',
            name='recycle_asset_using_person_jobcode',
        ),
        migrations.RemoveField(
            model_name='wasteasset',
            name='waste_asset_contract_code',
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='operator_jobcode',
            field=models.ForeignKey(blank=True, help_text='办理回收操作的人员工号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recycle_assets_operator', to='usermanagement.employee', to_field='employee_jobcode', verbose_name='回收操作人工号'),
        ),
        migrations.AlterField(
            model_name='assetoperationlog',
            name='asset_code',
            field=models.CharField(db_index=True, help_text='关联的资产编码', max_length=64, verbose_name='资产编码'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type_code', 'asset_current_status'], name='idx_asset_type_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_storage_code', 'asset_current_status'], name='idx_asset_storage_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_contract_code', 'asset_current_status'], name='idx_asset_contract_status'),
        ),
        migrations.RemoveField(
            model_name='outasset',
            name='outasset_applicant_jobcode',
        ),
        migrations.RemoveField(
            model_name='outasset',
            name='outasset_contract_code',
        ),
        migrations.RemoveField(
            model_name='outasset',
            name='outasset_current_status',
        ),
        migrations.RemoveField(
            model_name='outasset',
            name='outasset_manager_jobcode',
        ),
        migrations.RemoveField(
            model_name='outasset',
            name='outasset_using_location',
        ),
    ]
