# Generated by Django 5.2.3 on 2026-07-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0010_migrate_paid_record_to_json'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
