# Generated by Django 6.0.5 on 2026-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


def fill_assettype_recordcodes(apps, schema_editor):
    """为现有 AssetType 数据生成 recordcode"""
    AssetType = apps.get_model('assetmanagement', 'AssetType')
    import uuid
    from datetime import datetime
    for obj in AssetType.objects.all():
        if not obj.recordcode:
            obj.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            obj.save(update_fields=['recordcode'])


def fill_contract_recordcodes(apps, schema_editor):
    """为现有 Contract 数据生成 recordcode"""
    Contract = apps.get_model('assetmanagement', 'Contract')
    import uuid
    from datetime import datetime
    for obj in Contract.objects.all():
        if not obj.recordcode:
            obj.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            obj.save(update_fields=['recordcode'])


def fill_storage_recordcodes(apps, schema_editor):
    """为现有 Storage 数据生成 recordcode"""
    Storage = apps.get_model('assetmanagement', 'Storage')
    import uuid
    from datetime import datetime
    for obj in Storage.objects.all():
        if not obj.recordcode:
            obj.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            obj.save(update_fields=['recordcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0010_remove_redundant_fields'),
        ('usermanagement', '0004_department_is_deleted_department_recordcode_and_more'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
