# Generated by Django 6.0.5 on 2026-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


def fill_assettype_recordcodes(apps, schema_editor):
    """为现有 AssetType 数据生成 recordcode"""
    AssetType = apps.get_model('assetmanagement', 'AssetType')
    import uuid
    from datetime import datetime
    for obj in AssetType.objects.all():
        if not obj.recordcode:
            obj.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            obj.save(update_fields=['recordcode'])


def fill_contract_recordcodes(apps, schema_editor):
    """为现有 Contract 数据生成 recordcode"""
    Contract = apps.get_model('assetmanagement', 'Contract')
    import uuid
    from datetime import datetime
    for obj in Contract.objects.all():
        if not obj.recordcode:
            obj.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            obj.save(update_fields=['recordcode'])


def fill_storage_recordcodes(apps, schema_editor):
    """为现有 Storage 数据生成 recordcode"""
    Storage = apps.get_model('assetmanagement', 'Storage')
    import uuid
    from datetime import datetime
    for obj in Storage.objects.all():
        if not obj.recordcode:
            obj.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            obj.save(update_fields=['recordcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0010_remove_redundant_fields'),
        ('usermanagement', '0004_department_is_deleted_department_recordcode_and_more'),
    ]

    operations = [
        # Step 1: 添加 recordcode 字段
        migrations.AddField(
            model_name='assettype',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=32, null=True, unique=True, verbose_name='记录编码'),
        ),
        migrations.AddField(
            model_name='contract',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=32, null=True, unique=True, verbose_name='记录编码'),
        ),
        migrations.AddField(
            model_name='storage',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=32, null=True, unique=True, verbose_name='记录编码'),
        ),
        # Step 2: 为现有数据填充 recordcode
        migrations.RunPython(fill_assettype_recordcodes, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(fill_contract_recordcodes, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(fill_storage_recordcodes, reverse_code=migrations.RunPython.noop),
        # Step 3: 修改外键引用（改为 recordcode / asset_recordcode）
        migrations.AlterField(
            model_name='asset',
            name='asset_applicant_jobcode',
            field=models.ForeignKey(blank=True, help_text='资产申请人的工号（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_applicant', to='usermanagement.employee', to_field='recordcode', verbose_name='资产申请人工号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_contract_code',
            field=models.ForeignKey(blank=True, db_column='asset_contract_code', help_text='关联的采购合同（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assetmanagement.contract', to_field='recordcode', verbose_name='资产合同'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_entry_person_jobcode',
            field=models.ForeignKey(blank=True, help_text='办理入库的人员工号（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_entry', to='usermanagement.employee', to_field='recordcode', verbose_name='资产入库人工号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_manager_jobcode',
            field=models.ForeignKey(blank=True, help_text='资产保管人的工号（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_manager', to='usermanagement.employee', to_field='recordcode', verbose_name='资产保管人'),
        ),
        # Step 4: 移除 Asset.asset_recordcode 的 default（改为 save() 生成）
        migrations.AlterField(
            model_name='asset',
            name='asset_recordcode',
            field=models.CharField(blank=True, help_text='系统自动生成的入库记录编码', max_length=32, null=True, unique=True, verbose_name='记录编码'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_storage_code',
            field=models.ForeignKey(blank=True, help_text='资产当前所在仓库（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets', to='assetmanagement.storage', to_field='recordcode', verbose_name='存储仓库'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type_code',
            field=models.ForeignKey(help_text='关联的资产类型（通过 recordcode 关联）', on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets', to='assetmanagement.assettype', to_field='recordcode', verbose_name='资产类型'),
        ),
        # Step 5: 移除业务编码的 unique=True
        migrations.AlterField(
            model_name='assettype',
            name='asset_type_code',
            field=models.CharField(help_text='资产类型唯一编码', max_length=20, verbose_name='资产分类编码'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(help_text='合同唯一编码', max_length=20, verbose_name='合同编码'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(help_text='合同的完整名称', max_length=100, verbose_name='合同名称'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_code',
            field=models.CharField(help_text='仓库唯一编码，用于业务关联', max_length=20, verbose_name='仓库编码'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_name',
            field=models.CharField(help_text='仓库名称，用户可见的展示名称', max_length=100, verbose_name='仓库名称'),
        ),
        # Step 6: 修改其他外键引用
        migrations.AlterField(
            model_name='damagedasset',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='审批人的工号（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='damaged_assets_approver', to='usermanagement.employee', to_field='recordcode', verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='damagedasset',
            name='damaged_asset_code',
            field=models.OneToOneField(blank=True, help_text='待报废的资产编码（通过 asset_recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_asset', to='assetmanagement.asset', to_field='asset_recordcode', verbose_name='待报废资产编码'),
        ),
        migrations.AlterField(
            model_name='harddisksn',
            name='asset_code',
            field=models.ForeignKey(help_text='关联的资产编码（通过 asset_recordcode 关联）', on_delete=django.db.models.deletion.CASCADE, related_name='harddisk_sns', to='assetmanagement.asset', to_field='asset_recordcode', verbose_name='硬盘序列号对应资产编码'),
        ),
        migrations.AlterField(
            model_name='outasset',
            name='outasset_code',
            field=models.ForeignKey(blank=True, help_text='关联的资产编码（通过 asset_recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_assets', to='assetmanagement.asset', to_field='asset_recordcode', verbose_name='出库资产编码'),
        ),
        migrations.AlterField(
            model_name='recycleasset',
            name='operator_jobcode',
            field=models.ForeignKey(blank=True, help_text='办理回收操作的人员工号（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recycle_assets_operator', to='usermanagement.employee', to_field='recordcode', verbose_name='回收操作人工号'),
        ),
        migrations.AlterField(
            model_name='recycleasset',
            name='recycle_asset_code',
            field=models.ForeignKey(help_text='回收的资产编码（通过 asset_recordcode 关联）', on_delete=django.db.models.deletion.PROTECT, related_name='recycle_assets', to='assetmanagement.asset', to_field='asset_recordcode', verbose_name='回收资产编码'),
        ),
        migrations.AlterField(
            model_name='wasteasset',
            name='waste_asset_code',
            field=models.OneToOneField(help_text='已报废的资产编码（通过 asset_recordcode 关联）', on_delete=django.db.models.deletion.DO_NOTHING, related_name='waste_asset', to='assetmanagement.asset', to_field='asset_recordcode', verbose_name='已报废资产编码'),
        ),
        # Step 7: 添加条件唯一约束
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('asset_type_code',), name='unique_asset_type_code_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('contract_code',), name='unique_contract_code_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('contract_name',), name='unique_contract_name_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('storage_code',), name='unique_storage_code_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('storage_name',), name='unique_storage_name_not_deleted'),
        ),
    ]
