# Generated by Django 5.2.3 on 2026-07-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0010_migrate_paid_record_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_total_quantity',
        ),
    ]
