# Generated by Django 5.2.3 on 2026-07-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0011_remove_contract_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_warranty_period',
            field=models.IntegerField(blank=True, default=0, help_text='合同约定的质保期,可作为资产保修期的默认值', null=True, verbose_name='合同质保期(年)'),
        ),
    ]
