# Generated by Django 5.2.3 on 2026-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0012_update_contract_warranty_period_default'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
