# Generated by Django 5.2.3 on 2026-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0012_update_contract_warranty_period_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='已支付金额,默认为0', max_digits=12, verbose_name='已支付金额'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='未支付金额(自动计算)', max_digits=12, verbose_name='未支付金额'),
        ),
    ]
