# Generated by Django 5.2.3 on 2026-07-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0013_update_amount_fields_not_null'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assettype',
            name='idx_asset_type_parent_old',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='parent_code',
        ),
    ]
