# Generated by Django 5.2.3 on 2026-07-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0013_update_amount_fields_not_null'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
