# Generated by Django 5.2.3 on 2026-07-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0014_remove_assettype_parent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='paid_record',
            field=models.JSONField(blank=True, help_text='支付记录(JSON格式的支付明细)', null=True, verbose_name='支付记录'),
        ),
    ]
