# Generated by Django 5.2.3 on 2026-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0015_convert_paid_record_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetoperationlog',
            name='operator_jobcode',
            field=models.CharField(blank=True, db_index=True, help_text='执行操作的人员工号', max_length=20, null=True, verbose_name='操作人工号'),
        ),
    ]
