# Generated by Django 5.2.3 on 2026-08-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0016_alter_assetoperationlog_operator_jobcode'),
        ('usermanagement', '0013_alter_employee_auth_user_and_more'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
