# Generated by Django 5.2.3 on 2026-08-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0016_alter_assetoperationlog_operator_jobcode'),
        ('usermanagement', '0013_alter_employee_auth_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetstatelog',
            options={'verbose_name': '资产状态变更日志', 'verbose_name_plural': '资产状态变更日志'},
        ),
        migrations.RemoveIndex(
            model_name='assetstatelog',
            name='am_asset_st_asset_r_20f56b_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetstatelog',
            name='am_asset_st_from_st_c77ac5_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetstatelog',
            name='am_asset_st_operato_bad1ca_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='warranty_manually_modified',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_warranty_period',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='has_payment',
        ),
        migrations.AddField(
            model_name='assetstatelog',
            name='is_active',
            field=models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='assetstatelog',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='assetstatelog',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码'),
        ),
        migrations.AddField(
            model_name='assetstatelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='assetstatelog',
            name='version',
            field=models.IntegerField(default=1, help_text='乐观锁版本号', verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='parent_code',
            field=models.CharField(blank=True, help_text='【已废弃】迁移完成后将删除,新代码请使用 parent FK', max_length=32, null=True, verbose_name='父级编码(旧)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_total_quantity',
            field=models.IntegerField(blank=True, help_text='合同约定的总数量', null=True, verbose_name='合同总数量'),
        ),
        migrations.AlterField(
            model_name='assetoperationlog',
            name='operator_jobcode',
            field=models.CharField(blank=True, help_text='执行操作的人员工号', max_length=20, null=True, verbose_name='操作人工号'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='asset_recordcode',
            field=models.ForeignKey(help_text='关联的资产唯一标识码', on_delete=django.db.models.deletion.PROTECT, related_name='state_logs', to='assetmanagement.asset', to_field='recordcode', verbose_name='关联资产'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='business_doc_no',
            field=models.CharField(blank=True, default='', help_text='关联的业务单据号', max_length=128, verbose_name='关联业务单据号'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='from_state',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], help_text='变更前的资产状态', max_length=20, verbose_name='变更前状态'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='operator_employee',
            field=models.ForeignKey(blank=True, help_text='执行状态变更的操作人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_logs_operator', to='usermanagement.employee', to_field='recordcode', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='状态变更的原因说明', verbose_name='变更原因'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='to_state',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], help_text='变更后的资产状态', max_length=20, verbose_name='变更后状态'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='已支付金额,默认为0', max_digits=12, null=True, verbose_name='已支付金额'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_unpaid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='未支付金额(自动计算)', max_digits=12, null=True, verbose_name='未支付金额'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paid_record',
            field=models.TextField(blank=True, help_text='支付记录(可存储JSON格式的支付明细)', null=True, verbose_name='支付记录'),
        ),
        migrations.AddIndex(
            model_name='assetstatelog',
            index=models.Index(fields=['asset_recordcode'], name='am_asset_st_asset_r_f3bb94_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstatelog',
            index=models.Index(fields=['created_at'], name='am_asset_st_created_3f838b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstatelog',
            index=models.Index(fields=['is_deleted'], name='am_asset_st_is_dele_a11b73_idx'),
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['parent_code'], name='idx_asset_type_parent_old'),
        ),
    ]
