# Generated by Django 5.2.3 on 2026-08-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0017_alter_assetstatelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outasset',
            name='outasset_type',
            field=models.CharField(blank=True, choices=[('receive', '领用'), ('borrow', '借用'), ('reissue', '重新发放')], default='receive', help_text='出库类型:领用/借用', max_length=50, null=True, verbose_name='出库类型'),
        ),
    ]
