# Generated by Django 5.2.3 on 2026-08-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0017_alter_assetstatelog_options_and_more'),
    ]

    operations = [
        # Stripped: Branch B ops are no-ops (covered by Branch A + 0020/0021)
    ]
