# Generated by Django 5.2.17 on 2026-08-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0012_fill_recordcodes'),
        ('assetmanagement', '0018_alter_outasset_outasset_type'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
