# Generated by Django 5.2.17 on 2026-08-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0019_merge_20260824_1949'),
        ('usermanagement', '0015_permission_role_rolepermission_userrole_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assettype',
            new_name='idx_asset_type_parent_old',
            old_name='am_asset_ty_parent__8acf11_idx',
        ),
        migrations.AddField(
            model_name='assettype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父级资产类型(FK 指向 recordcode),null 表示顶级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assetmanagement.assettype', to_field='recordcode', verbose_name='父级类型'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='path',
            field=models.CharField(blank=True, default='', help_text='从根到当前节点的完整路径,如 /ASSETTYPE-001/IT-001/DEV-001', max_length=500, verbose_name='物化路径'),
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='broken_reason',
            field=models.CharField(blank=True, help_text='回收时发现损坏的原因', max_length=100, null=True, verbose_name='损坏原因'),
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='is_broken',
            field=models.BooleanField(default=False, help_text='回收时是否发现资产损坏', verbose_name='回收时发现损坏'),
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='is_lost',
            field=models.BooleanField(default=False, help_text='回收时是否发现资产遗失', verbose_name='回收时发现遗失'),
        ),
        migrations.AddField(
            model_name='recycleasset',
            name='lost_reason',
            field=models.CharField(blank=True, help_text='回收时发现遗失的原因', max_length=100, null=True, verbose_name='遗失原因'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_current_status',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], db_index=True, default='in_store', help_text='资产状态:在库/已回收待发放/在用/已损坏/维修中/已遗失/待报废/已报废', max_length=20, verbose_name='资产当前状态'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='physical_grade',
            field=models.CharField(choices=[('excellent', '全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='good', help_text='资产物理成色:全新/良好/一般/较差', max_length=20, verbose_name='物理成色'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usage_type',
            field=models.CharField(choices=[('new', '全新'), ('used', '二手'), ('refurbished', '翻新')], default='new', help_text='资产使用性质:全新/二手/翻新', max_length=20, verbose_name='使用性质'),
        ),
        migrations.AlterField(
            model_name='assetoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('out', '出库'), ('recycle', '回收'), ('broken', '已损坏'), ('lost', '已遗失'), ('found', '找回'), ('damaged', '待报废'), ('waste', '已报废'), ('repair', '送修'), ('repair_done', '维修完成'), ('repair_failed', '维修失败'), ('approve', '审批'), ('transfer', '转移'), ('state_change', '状态变更')], db_index=True, help_text='操作类型', max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='from_state',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], help_text='变更前的资产状态', max_length=20, verbose_name='变更前状态'),
        ),
        migrations.AlterField(
            model_name='assetstatelog',
            name='to_state',
            field=models.CharField(choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失'), ('damaged', '待报废'), ('scrapped', '已报废')], help_text='变更后的资产状态', max_length=20, verbose_name='变更后状态'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='parent_code',
            field=models.CharField(blank=True, help_text='【已废弃】迁移完成后将删除,新代码请使用 parent FK', max_length=32, null=True, verbose_name='父级编码(旧)'),
        ),
        migrations.AlterField(
            model_name='damagedasset',
            name='original_status',
            field=models.CharField(blank=True, choices=[('in_store', '在库'), ('in_use', '在用'), ('recycled_pending', '已回收待发放'), ('broken', '已损坏'), ('repairing', '维修中'), ('lost', '已遗失')], help_text='进入damaged前的资产状态,用于reject时回退', max_length=20, null=True, verbose_name='原状态'),
        ),
        migrations.AlterField(
            model_name='foundasset',
            name='lost_asset_recordcode',
            field=models.OneToOneField(help_text='关联的遗失资产记录', on_delete=django.db.models.deletion.PROTECT, related_name='found_record', to='assetmanagement.lostasset', to_field='recordcode', verbose_name='关联的遗失记录'),
        ),
        migrations.AlterField(
            model_name='outasset',
            name='outasset_type',
            field=models.CharField(blank=True, choices=[('receive', '领用'), ('borrow', '借用'), ('reissue', '重新发放')], default='receive', help_text='出库类型:领用/借用', max_length=50, null=True, verbose_name='出库类型'),
        ),
        migrations.AlterField(
            model_name='recycleasset',
            name='recycle_type',
            field=models.CharField(blank=True, choices=[('normal', '正常回收'), ('abnormal', '异常回收'), ('other', '其他')], help_text='回收原因/类型', max_length=50, null=True, verbose_name='回收类型'),
        ),
        migrations.AlterField(
            model_name='repairasset',
            name='physical_grade_after',
            field=models.CharField(blank=True, choices=[('excellent', '全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], help_text='维修后的物理成色', max_length=20, null=True, verbose_name='维修后成色'),
        ),
        migrations.AlterField(
            model_name='repairasset',
            name='physical_grade_before',
            field=models.CharField(blank=True, choices=[('excellent', '全新'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], help_text='维修前的物理成色', max_length=20, null=True, verbose_name='维修前成色'),
        ),
        migrations.AlterField(
            model_name='wasteasset',
            name='damaged_recordcode',
            field=models.OneToOneField(blank=True, help_text='关联的待报废记录的资产唯一标识码,用于追溯来源', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_asset_record', to='assetmanagement.damagedasset', to_field='recordcode', verbose_name='来源待报废记录的资产唯一标识码'),
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['parent'], name='idx_asset_type_parent_fk'),
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['path'], name='idx_asset_type_path'),
        ),
        migrations.AddConstraint(
            model_name='repairasset',
            constraint=models.UniqueConstraint(condition=models.Q(('repair_status', 'in_progress')), fields=('asset_recordcode',), name='uniq_active_repair_per_asset'),
        ),
    ]
