# Generated by Django 6.0.5 on 2026-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0021_alter_assetoperationlog_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='qr_code',
            field=models.CharField(blank=True, help_text='二维码内容,存储扫码查看资产详情的链接(如 {base_url}/scan/{recordcode}/)', max_length=200, null=True, verbose_name='二维码'),
        ),
    ]
