# Generated by Django 5.2.17 on 2026-09-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0022_alter_asset_qr_code'),
        ('usermanagement', '0017_seed_system_config_manage_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedasset',
            name='asset_recordcode',
            field=models.ForeignKey(blank=True, help_text='待报废的资产唯一标识码(通过 recordcode 关联)。由 Partial Unique Constraint 保证仅非软删记录唯一,软删(驳回/取消)释放槽位以便重新申请', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damaged_assets', to='assetmanagement.asset', to_field='recordcode', verbose_name='待报废资产的资产唯一标识码'),
        ),
        migrations.AddConstraint(
            model_name='damagedasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('asset_recordcode',), name='uq_damaged_asset_active_asset', violation_error_message='同一资产仅允许存在一条未删除的待报废记录'),
        ),
    ]
