# Generated by Django 5.2.3 on 2026-07-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_jobcode', models.CharField(help_text='通知接收人的 employee_jobcode', max_length=50, verbose_name='接收人工号')),
                ('notification_type', models.CharField(choices=[('approval', '审批通知'), ('status_change', '状态变更'), ('system', '系统通知')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_asset_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联资产编码')),
                ('related_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='关联页面路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'am_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_jobcode', 'is_read'], name='am_notifica_recipie_055048_idx'), models.Index(fields=['created_at'], name='am_notifica_created_502c12_idx')],
            },
        ),
    ]
