# Generated by Django 5.2.3 on 2026-07-19 01:27

from django.db import migrations, models


def populate_recordcodes(apps, schema_editor):
    """为现有通知记录生成 recordcode"""
    from core.models import generate_recordcode_with_prefix
    Notification = apps.get_model('notification', 'Notification')
    for notification in Notification.objects.filter(recordcode__isnull=True):
        notification.recordcode = generate_recordcode_with_prefix('NTF')
        notification.save(update_fields=['recordcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间'),
        ),
        migrations.RunPython(populate_recordcodes, migrations.RunPython.noop),
    ]
