# Generated by Django 6.0.5 on 2026-05-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=20, unique=True, verbose_name='部门编码')),
                ('department_name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('department_information', models.CharField(max_length=20, verbose_name='部门信息员')),
            ],
            options={
                'verbose_name': '部门管理',
                'verbose_name_plural': '部门管理',
                'db_table': 'department_database_table',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_jobcode', models.CharField(max_length=20, unique=True, verbose_name='员工工号')),
                ('employee_name', models.CharField(max_length=100, verbose_name='员工名称')),
                ('employee_status', models.CharField(choices=[('active', '在职员工'), ('left', '离职员工'), ('retirement', '退休员工')], default='active', max_length=10, verbose_name='员工状态')),
                ('employee_phone', models.CharField(max_length=15, unique=True, verbose_name='员工电话')),
                ('employee_location', models.CharField(max_length=100, verbose_name='员工位置')),
                ('employee_description', models.TextField(blank=True, null=True, verbose_name='员工描述')),
                ('employee_department', models.ForeignKey(blank=True, default='Error', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usermanagement.department', to_field='department_code', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工管理',
                'verbose_name_plural': '员工管理',
                'db_table': 'user_database_table',
                'ordering': ['employee_jobcode'],
                'indexes': [models.Index(fields=['employee_jobcode'], name='user_databa_employe_6dfa3c_idx'), models.Index(fields=['employee_name'], name='user_databa_employe_1dc263_idx')],
            },
        ),
    ]
