# Generated by Django 6.0.5 on 2026-07-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('recordcode', models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('department_code', models.CharField(help_text='部门唯一标识编码', max_length=20, verbose_name='部门编码')),
                ('department_name', models.CharField(help_text='部门显示名称', max_length=100, verbose_name='部门名称')),
                ('department_information', models.CharField(help_text='部门信息负责人', max_length=20, verbose_name='部门信息员')),
                ('parent_code', models.CharField(blank=True, help_text='上级部门编码，null 表示根部门', max_length=20, null=True, verbose_name='上级部门编码')),
                ('level', models.IntegerField(default=0, help_text='部门层级：0=根部门，1=一级部门，最大 6 层', verbose_name='部门层级')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小排序越靠前，用于控制前端显示顺序', verbose_name='排序顺序')),
            ],
            options={
                'verbose_name': '部门管理',
                'verbose_name_plural': '部门管理',
                'db_table': 'am_department',
                'ordering': ['sort_order', 'department_code'],
                'indexes': [models.Index(fields=['parent_code'], name='idx_department_parent'), models.Index(fields=['level'], name='idx_department_level')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('department_code',), name='unique_department_code_not_deleted'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('department_name',), name='unique_department_name_not_deleted')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('recordcode', models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('employee_jobcode', models.CharField(max_length=20, verbose_name='员工工号')),
                ('employee_name', models.CharField(max_length=100, verbose_name='员工名称')),
                ('employee_status', models.CharField(choices=[('active', '在职员工'), ('left', '离职员工'), ('retirement', '退休员工')], default='active', max_length=10, verbose_name='员工状态')),
                ('employee_phone', models.CharField(max_length=15, verbose_name='员工电话')),
                ('employee_location', models.CharField(max_length=100, verbose_name='员工位置')),
                ('employee_description', models.TextField(blank=True, null=True, verbose_name='员工描述')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小排序越靠前，用于控制前端显示顺序', verbose_name='排序顺序')),
                ('employee_department', models.ForeignKey(blank=True, help_text='所属部门（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.department', to_field='recordcode', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工管理',
                'verbose_name_plural': '员工管理',
                'db_table': 'am_employee',
                'ordering': ['sort_order', 'employee_jobcode'],
                'indexes': [models.Index(fields=['employee_jobcode'], name='am_employee_employe_d7c7fb_idx'), models.Index(fields=['employee_name'], name='am_employee_employe_7ff30e_idx'), models.Index(fields=['sort_order'], name='am_employee_sort_or_9aa8c6_idx'), models.Index(fields=['employee_department'], name='idx_employee_department')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_jobcode',), name='unique_employee_jobcode_not_deleted'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_phone',), name='unique_employee_phone_not_deleted')],
            },
        ),
    ]
