# Generated by Django 6.0.5 on 2026-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['sort_order', 'department_code'], 'verbose_name': '部门管理', 'verbose_name_plural': '部门管理'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['sort_order', 'employee_jobcode'], 'verbose_name': '员工管理', 'verbose_name_plural': '员工管理'},
        ),
        migrations.AddField(
            model_name='department',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小排序越靠前，用于控制前端显示顺序', verbose_name='排序顺序'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小排序越靠前，用于控制前端显示顺序', verbose_name='排序顺序'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['sort_order'], name='user_databa_sort_or_131b07_idx'),
        ),
    ]
