# Generated by Django 6.0.5 on 2026-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        # Stripped: parallel-branch ops are no-ops
    ]
