# Generated by Django 6.0.5 on 2026-05-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        # Stripped: parallel-branch ops are no-ops
    ]
