# Generated by Django 5.2.3 on 2026-07-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_fix_parent_fk_to_recordcode'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
