# Generated by Django 6.0.5 on 2026-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


def fill_department_recordcodes(apps, schema_editor):
    """为现有 Department 数据生成 recordcode"""
    Department = apps.get_model('usermanagement', 'Department')
    import uuid
    from datetime import datetime
    for dept in Department.objects.all():
        if not dept.recordcode:
            dept.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            dept.save(update_fields=['recordcode'])


def fill_employee_recordcodes(apps, schema_editor):
    """为现有 Employee 数据生成 recordcode"""
    Employee = apps.get_model('usermanagement', 'Employee')
    import uuid
    from datetime import datetime
    for emp in Employee.objects.all():
        if not emp.recordcode:
            emp.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            emp.save(update_fields=['recordcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_add_department_tree_fields'),
    ]

    operations = [
        # Step 1: 添加 is_deleted 和 recordcode 字段
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='department',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=32, null=True, unique=True, verbose_name='记录编码'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='employee',
            name='recordcode',
            field=models.CharField(blank=True, help_text='后端生成的全局唯一编码，用于外键引用', max_length=32, null=True, unique=True, verbose_name='记录编码'),
        ),
        # Step 2: 为现有数据填充 recordcode
        migrations.RunPython(fill_department_recordcodes, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(fill_employee_recordcodes, reverse_code=migrations.RunPython.noop),
        # Step 3: 修改外键引用（从 department_code 改为 recordcode）
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(blank=True, default='Error', help_text='所属部门（通过 recordcode 关联）', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usermanagement.department', to_field='recordcode', verbose_name='所属部门'),
        ),
        # Step 4: 移除 department_code 的 unique（此时已无外键引用它）
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(help_text='部门唯一标识编码', max_length=20, verbose_name='部门编码'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(help_text='部门显示名称', max_length=100, verbose_name='部门名称'),
        ),
        # Step 5: 移除 employee_jobcode/employee_phone 的 unique
        migrations.AlterField(
            model_name='employee',
            name='employee_jobcode',
            field=models.CharField(max_length=20, verbose_name='员工工号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(max_length=15, verbose_name='员工电话'),
        ),
        # Step 6: 添加条件唯一约束
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('department_code',), name='unique_department_code_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('department_name',), name='unique_department_name_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_jobcode',), name='unique_employee_jobcode_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_phone',), name='unique_employee_phone_not_deleted'),
        ),
    ]
