# Generated by Django 6.0.5 on 2026-06-11 04:13

import django.db.models.deletion
from django.db import migrations, models


def fill_department_recordcodes(apps, schema_editor):
    """为现有 Department 数据生成 recordcode"""
    Department = apps.get_model('usermanagement', 'Department')
    import uuid
    from datetime import datetime
    for dept in Department.objects.all():
        if not dept.recordcode:
            dept.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            dept.save(update_fields=['recordcode'])


def fill_employee_recordcodes(apps, schema_editor):
    """为现有 Employee 数据生成 recordcode"""
    Employee = apps.get_model('usermanagement', 'Employee')
    import uuid
    from datetime import datetime
    for emp in Employee.objects.all():
        if not emp.recordcode:
            emp.recordcode = f"REC-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:8].upper()}"
            emp.save(update_fields=['recordcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_add_department_tree_fields'),
    ]

    operations = [
        # Stripped: parallel-branch ops are no-ops
    ]
