# Generated by Django 5.2.3 on 2026-07-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_alter_employee_auth_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='department',
            name='idx_department_parent_old',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent_code',
        ),
    ]
