# Generated by Django 5.2.3 on 2026-07-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_alter_employee_auth_user_and_more'),
    ]

    operations = [
        # Stripped: all ops are no-ops (0001_initial + consolidated is source of truth)
    ]
