# Generated by Django 5.2.3 on 2026-08-12 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0012_grant_unregistered_write_to_asset_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='auth_user',
            field=models.OneToOneField(blank=True, help_text='绑定的认证账号 FK,null 表示未绑定。绑定请通过 EmployeeService.bind_auth_user(),禁止直接写库', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='绑定的认证账号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_jobcode',
            field=models.CharField(max_length=20, verbose_name='员工工号'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_code',
            field=models.CharField(help_text='格式:module:action,如 asset:create', max_length=100, verbose_name='权限编码'),
        ),
    ]
