# Generated by Django 5.2.17 on 2026-08-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_fill_recordcodes'),
        ('usermanagement', '0013_alter_employee_auth_user_and_more'),
    ]

    operations = [
    ]
