# Generated by Django 5.2.17 on 2026-08-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0014_merge_20260824_1949'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('recordcode', models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('permission_code', models.CharField(help_text='格式:module:action,如 asset:create', max_length=100, verbose_name='权限编码')),
                ('module', models.CharField(help_text='所属模块,如 asset、outasset', max_length=50, verbose_name='模块')),
                ('action', models.CharField(help_text='操作类型,如 read、create、update、delete', max_length=50, verbose_name='操作')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='权限描述')),
            ],
            options={
                'verbose_name': '权限点管理',
                'verbose_name_plural': '权限点管理',
                'db_table': 'am_permission',
                'ordering': ['module', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('recordcode', models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('role_code', models.CharField(help_text='唯一标识,如 system_admin', max_length=50, verbose_name='角色编码')),
                ('role_name', models.CharField(help_text='显示名称,如 系统管理员', max_length=100, verbose_name='角色名称')),
                ('role_level', models.IntegerField(default=0, help_text='层级值:5/4/3/2/1,用于兼容旧权限判断', verbose_name='层级值')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='角色描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统内置角色不可删除', verbose_name='系统内置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
                'db_table': 'am_role',
                'ordering': ['-role_level', 'sort_order', 'role_code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('recordcode', models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '角色权限关联',
                'verbose_name_plural': '角色权限关联',
                'db_table': 'am_role_permission',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='更新时间')),
                ('recordcode', models.CharField(blank=True, help_text='后端生成的全局唯一编码,用于外键引用', max_length=64, null=True, unique=True, verbose_name='记录编码')),
                ('is_active', models.BooleanField(default=True, help_text='控制记录是否激活', verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否删除')),
                ('data_scope', models.JSONField(blank=True, default=dict, help_text='JSON 格式:{"scope_type": "all"} 或 {"scope_type": "department", "department_code": "IT-001", "include_children": true}', verbose_name='数据范围')),
            ],
            options={
                'verbose_name': '用户角色关联',
                'verbose_name_plural': '用户角色关联',
                'db_table': 'am_user_role',
            },
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='idx_department_parent',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent_code',
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='上级部门(FK 指向 recordcode),null 表示根部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='usermanagement.department', to_field='recordcode', verbose_name='上级部门'),
        ),
        migrations.AddField(
            model_name='department',
            name='path',
            field=models.CharField(blank=True, default='', help_text='从根到当前节点的完整路径,如 /DEPT-001/IT-001/DEV-001', max_length=500, verbose_name='物化路径'),
        ),
        migrations.AddField(
            model_name='employee',
            name='auth_user',
            field=models.OneToOneField(blank=True, help_text='绑定的认证账号 FK,null 表示未绑定。绑定请通过 EmployeeService.bind_auth_user(),禁止直接写库', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='绑定的认证账号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('system_admin', '系统管理员'), ('dept_manager', '部门经理'), ('asset_admin', '资产管理员'), ('regular_user', '普通用户'), ('auditor', '审计员')], default='regular_user', help_text='RBAC 角色:system_admin/dept_manager/asset_admin/regular_user/auditor', max_length=20, verbose_name='系统角色'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='idx_department_parent_fk'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['path'], name='idx_department_path'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('auth_user',), name='unique_employee_auth_user_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('permission_code',), name='unique_permission_code_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('module', 'action'), name='unique_module_action_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('role_code',), name='unique_role_code_not_deleted'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='usermanagement.permission', verbose_name='权限点'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='usermanagement.role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='系统账号'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='usermanagement.role', verbose_name='角色'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['auth_user'], name='idx_ur_auth_user'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='idx_ur_role'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('auth_user', 'role'), name='unique_user_role'),
        ),
    ]
